/*
 * This file is generated by jOOQ.
 */
package com.test.kotlinjooq.db.mysql


import com.test.kotlinjooq.db.mysql.tables.Author
import com.test.kotlinjooq.db.mysql.tables.Book

import kotlin.collections.List

import org.jooq.Catalog
import org.jooq.Table
import org.jooq.impl.SchemaImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class Testdb : SchemaImpl("testdb", DefaultCatalog.DEFAULT_CATALOG) {
    companion object {

        /**
         * The reference instance of <code>testdb</code>
         */
        val TESTDB = Testdb()
    }

    /**
     * The table <code>testdb.author</code>.
     */
    val AUTHOR get() = Author.AUTHOR

    /**
     * The table <code>testdb.book</code>.
     */
    val BOOK get() = Book.BOOK

    override fun getCatalog(): Catalog = DefaultCatalog.DEFAULT_CATALOG

    override fun getTables(): List<Table<*>> = listOf(
        Author.AUTHOR,
        Book.BOOK
    )
}
