/*
 * This file is generated by jOOQ.
 */
package com.test.kotlinjooq.db.mysql.keys


import com.test.kotlinjooq.db.mysql.tables.Author
import com.test.kotlinjooq.db.mysql.tables.Book
import com.test.kotlinjooq.db.mysql.tables.records.AuthorRecord
import com.test.kotlinjooq.db.mysql.tables.records.BookRecord

import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal



// -------------------------------------------------------------------------
// UNIQUE and PRIMARY KEY definitions
// -------------------------------------------------------------------------

val KEY_AUTHOR_PRIMARY: UniqueKey<AuthorRecord> = Internal.createUniqueKey(Author.AUTHOR, DSL.name("KEY_author_PRIMARY"), arrayOf(Author.AUTHOR.ID), true)
val KEY_BOOK_PRIMARY: UniqueKey<BookRecord> = Internal.createUniqueKey(Book.BOOK, DSL.name("KEY_book_PRIMARY"), arrayOf(Book.BOOK.ID), true)
