/*
 * This file is generated by jOOQ.
 */
package com.test.kotlinjooq.db.mysql.tables.references


import com.test.kotlinjooq.db.mysql.tables.Author
import com.test.kotlinjooq.db.mysql.tables.Book



/**
 * The table <code>testdb.author</code>.
 */
val AUTHOR = Author.AUTHOR

/**
 * The table <code>testdb.book</code>.
 */
val BOOK = Book.BOOK
